apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30080
  selector:
    app: backend
  type: NodePort

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: freshcart-backend:latest
          imagePullPolicy: Never # Force Kubernetes to use the local docker image built inside minikube
          ports:
            - containerPort: 8000
          env:
            - name: MONGODB_URI
              value: "mongodb://admin:freshcart123@mongo:27017/freshcartdb?authSource=admin"
            - name: REDIS_URL
              value: "redis://redis:6379/0"
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: "kafka:9092"
            - name: JWT_SECRET
              value: "freshcart-secret-key-change-this-in-production"
          livenessProbe:
            httpGet:
              path: /api/products
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /api/products
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 10
